fix unpack for lua 5.1
stefano-m/lua-dbus_proxy pull request #5
Opened 2020-03-08 17:07 UTC by unai-ndz

`table.unpack` is only available on `lua >= 5.2`.

This makes `dbus_proxy` also work with `lua 5.1`

2020-04-10 06:11 UTC, stefano-m commented
Hello,

thanks for your interest in this project and your contribution and sorry for the very late reply.

I am a little reluctant in including this change because I would be unable to support Lua 5.1 properly.

Would you be willing to add a Lua 5.1 configuration to the `.travis.yml` file so we can at least run tests against it?

Thanks.

2020-04-10 06:21 UTC, stefano-m requested changes
All looks good. But I would like to have Travis CI running the tests against Lua 5.1 too. Do you think you can add that?

2020-04-10 20:23 UTC, unai-ndz commented
As travis has shown, support for `lua 5.1` will need a few more changes and I'm actually using `luajit` which I think is the only advantage of not running a newer version.

2020-04-14 19:55 UTC, stefano-m approved these changes

2020-04-14 20:09 UTC, stefano-m commented
Pulled in by 412ff3ebeb1569dd056f7c88fb24f803d3f2e834

Thank you!

2020-04-14 20:09 UTC, closed without merging